### ISSUE TITLE
确认到店，优化，分辨率 1280*800还有1366*768的情况下，点击订单，弹出的页面。显示不完整

### ISSUE THREAD

**Issue by liuyigegeshuaiqi** [liuyigegeshuaiqi/weixun#24]
![image](https://user-images.githubusercontent.com/39045032/138057639-88f6ca45-5e48-4887-acda-47d08ec05fab.png)

**Comment by liuyigegeshuaiqi** [comment]
以优化

**Comment by ahuyil** [comment]
右侧弹出层 整体加上滚动条了， 可以解决低分辨率下 显示不完成的问题了。
