### ISSUE TITLE
到店确认，优化，批量删除按钮的之前如果点击了删除订单的其中一个，如果没有点击其他的订单，眼睛的功能会一直保存删除订单的数据

### ISSUE THREAD

**Issue by liuyigegeshuaiqi** [liuyigegeshuaiqi/weixun#25]
![1634720054(1)](https://user-images.githubusercontent.com/39045032/138061433-5e7a6776-3cf1-4b76-94d1-fa514a1a29ca.jpg)

**Comment by ahuyil** [comment]
这个是之前提需求， 你们要一直保持选择的订单的数据，才特意这样搞的呀！

**Comment by liuyigegeshuaiqi** [comment]
因为我认为删除后，把删除的订单保存是没有意义的。

**Comment by liuyigegeshuaiqi** [comment]
已验证
