### ISSUE TITLE
基本设置-基本设置，接待订单，联系号码拨打顺序缺少选择框名，同时删除其中一个，保存按钮没有高亮

### ISSUE THREAD

**Issue by liuyigegeshuaiqi** [liuyigegeshuaiqi/weixun#5]
![image](https://user-images.githubusercontent.com/39045032/137865203-30a29471-2f88-476e-b3ab-a61ca0bfb98b.png)
![image](https://user-images.githubusercontent.com/39045032/137865519-18e61a3b-cb73-41a9-9ef1-f80946857755.png)

**Comment by ahuyil** [comment]
已解决
